### ISSUE TITLE
Had problem when build windows/android

### ISSUE THREAD

**Issue by trihdm95** [yannbf/ionic2-components#61]
**Cannot build it on android/windows**  

**Steps to reproduce the bug:**
Error: ./src/pages/miscellaneous/real-estate-listing/real-estate-listing.ts
Module parse failed: Unexpected token (40:653)
You may need an appropriate loader to handle this file type.
|     RealEstateListingPage = __decorate([
|         Component({
|             selector: 'page-real-estate-listing',template:/*ion-inline-start:"/home/tri/Desktop/ionic3-components-master/src/pages/miscellaneous/real-estate-listing/real-estate-listing.html"*/`<ion-header no-border>\n  <ion-navbar>\n    <ion-title>\n      {{estateProperty.name}}\n    </ion-title>\n  </ion-navbar>\n</ion-header>\n\n<ion-content fullscreen elestic-header>\n  <section class="housing-image"\n           [ngStyle]="{ \'background-image\': \'url(\' + estateProperty.image + \')\'}">\n    <section class="housing-banner" padding>\n      <span class="housing-title">{{estateProperty.name}}</span>\n      <span class="price">${{estateProperty.price}}</span>\n    </section>\n  </section>\n  <section class="main-content">\n    <ion-grid class="main-features">\n      <ion-row>\n        <ion-col text-center *ngFor="let feature of estateProperty.features">\n          <ion-icon [name]="feature.icon"></ion-icon>\n          <span class="item-block">{{feature.title}}</span>\n        </ion-col>\n      </ion-row>\n    </ion-grid>\n    <ion-grid class="listing-details">\n      <ion-row>\n        <p margin-left margin-right no-margin-top style="text-align: justify">\n          {{estateProperty.description}}\n        </p>\n      </ion-row>\n      <ion-row>\n        <ion-col>\n          <ion-icon name="home"></ion-icon>{{estateProperty.style}}\n        </ion-col>\n        <ion-col>\n          <ion-icon name="pin"></ion-icon>{{estateProperty.size}}\n        </ion-col>\n      </ion-row>\n      <ion-row *ngFor="let a of [1,1,1,1,1,1,1,1,1,1]">\n        <ion-col>\n          info here\n        </ion-col>\n      </ion-row>\n    </ion-grid>\n  </section>\n</ion-content>\n<ion-footer>\n  <button ion-button large full no-margin color="danger" >\n    get in touch now\n  </button>\n</ion-footer>`/*ion-inline-end:"/home/tri/Desktop/ionic3-components-master/src/pages/miscellaneous/real-estate-listing/real-estate-listing.html"*/,
|         }),
|         __metadata("design:paramtypes", [NavController])
 @ ./src/pages/miscellaneous/real-estate-listing/real-estate-listing.module.ts 10:0-62
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./node_modules/ionic-angular/util/module-loader.js
 @ ./node_modules/ionic-angular/components/popover/popover-component.js
 @ ./node_modules/ionic-angular/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
    at new BuildError (/home/tri/Desktop/ionic3-components-master/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/home/tri/Desktop/ionic3-components-master/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/home/tri/Desktop/ionic3-components-master/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/home/tri/Desktop/ionic3-components-master/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/home/tri/Desktop/ionic3-components-master/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/home/tri/Desktop/ionic3-components-master/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/home/tri/Desktop/ionic3-components-master/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/tri/Desktop/ionic3-components-master/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/tri/Desktop/ionic3-components-master/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/tri/Desktop/ionic3-components-master/node_modules/webpack/lib/Compiler.js:365:9)

**Important information:**

**Comment by thepoojam** [comment]
we also getting same issue , please let me know how to solve this issue..
